---
- name: create ubuntu device
  hosts: localhost
  connection: local
  vars:
    build: present
  tasks:
  - name: create or discover packet devices
    packet_device:
      project_id: "{{project_id}}"
      hostnames: [control,compute1,compute2]
      operating_system: ubuntu_16_04
      plan: baremetal_0
      facility: sjc1
      state: "{{build}}"
      wait_for_public_IPv: 4
    register: packet_info
  - name: show packet name and IP
    debug:
      msg: "{{item.hostname}}:{{item.public_ipv4}}  "
    with_items: "{{packet_info['devices']}}"
  - name: create inventory from template and packet_info results
    template:
      src: templates/inventory.j2
      dest: inventory
